name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -o ./publish/x64
          dotnet publish -c Release -r win-arm64 --self-contained true -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -o ./publish/arm64

      - name: Run Tests
        run: dotnet test --verbosity normal

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: LiveCaptionsTranslator
          path: ./publish

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: LiveCaptionsTranslator
          path: ./release

      - name: Create ZIP Files
        run: |
          cd release
          zip -r LiveCaptionsTranslator-win-x64.zip x64
          zip -r LiveCaptionsTranslator-win-arm64.zip arm64

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/LiveCaptionsTranslator-win-x64.zip
            release/LiveCaptionsTranslator-win-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
